# Sun Energy Optimization: Exploratory Data Analysis (EDA)

## Dataset Overview

## Solar Radiation Measurement Data for Siera Leone

This dataset is sourced and compiled from EnergyData.info. Each record includes values for solar radiation, air temperature, relative humidity, barometric pressure, precipitation, wind speed, wind direction, radiance sensor data (clean and soiled), soiling measurements, and cleaning events.

### Imports and Reading Data

In [1]:
# Import Essentials Library
import pandas as pd
import numpy as np

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
sierraleone_df = pd.read_csv('../assets/data/sierraleone-bumbuna.csv')

### Data Understanding

In [5]:
sierraleone_df.head(15)

,Timestamp,GHI,DNI,DHI,ModA,ModB,Tamb,RH,WS,WSgust,WSstdev,WD,WDstdev,BP,Cleaning,Precipitation,TModA,TModB,Comments
0,2021-10-30 00:01,-0.7,-0.1,-0.8,0.0,0.0,21.9,99.1,0.0,0.0,0.0,0.0,0.0,1002,0,0.0,22.3,22.6,NaN
1,2021-10-30 00:02,-0.7,-0.1,-0.8,0.0,0.0,21.9,99.2,0.0,0.0,0.0,0.0,0.0,1002,0,0.0,22.3,22.6,NaN
2,2021-10-30 00:03,-0.7,-0.1,-0.8,0.0,0.0,21.9,99.2,0.0,0.0,0.0,0.0,0.0,1002,0,0.0,22.3,22.6,NaN
3,2021-10-30 00:04,-0.7,0.0,-0.8,0.0,0.0,21.9,99.3,0.0,0.0,0.0,0.0,0.0,1002,0,0.1,22.3,22.6,NaN
4,2021-10-30 00:05,-0.7,-0.1,-0.8,0.0,0.0,21.9,99.3,0.0,0.0,0.0,0.0,0.0,1002,0,0.0,22.3,22.6,NaN
5,2021-10-30 00:06,-0.7,-0.1,-0.8,0.0,0.0,21.9,99.3,0.0,0.0,0.0,0.0,0.0,1002,0,0.0,22.3,22.7,NaN
6,2021-10-30 00:07,-0.7,0.0,-0.8,0.0,0.0,22.0,99.4,0.1,0.7,0.2,240.4,0.0,1002,0,0.0,22.3,22.7,NaN
7,2021-10-30 00:08,-0.7,0.0,-0.8,0.0,0.0,22.0,99.5,0.2,0.7,0.4,233.5,1.6,1002,0,0.0,22.4,22.7,NaN
8,2021-10-30 00:09,-0.7,-0.1,-0.8,0.0,0.0,22.0,99.5,0.7,1.1,0.5,232.0,0.3,1002,0,0.0,22.4,22.7,NaN
9,2021-10-30 00:10,-0.7,-0.1,-0.8,0.0,0.0,21.9,99.2,0.6,1.1,0.5,232.5,0.3,1002,0,0.0,22.4,22.7,NaN
10,2021-10-30 00:11,-0.7,-0.1,-0.8,0.0,0.0,21.9,99.3,0.4,0.7,0.5,234.4,0.1,1002,0,0.1,22.4,22.7,NaN
11,2021-10-30 00:12,-0.7,-0.1,-0.8,0.0,0.0,22.0,99.4,0.7,1.1,0.5,238.1,1.3,1002,0,0.0,22.4,22.7,NaN
12,2021-10-30 00:13,-0.7,0.0,-0.8,0.0,0.0,22.0,99.5,0.2,0.7,0.4,251.4,2.7,1002,0,0.0,22.4,22.7,NaN
13,2021-10-30 00:14,-0.7,-0.1,-0.8,0.0,0.0,22.0,99.4,0.0,0.0,0.0,0.0,0.0,1002,0,0.0,22.4,22.7,NaN
14,2021-10-30 00:15,-0.6,-0.1,-0.8,0.0,0.0,21.9,99.3,0.0,0.0,0.0,0.0,0.0,1002,0,0.0,22.4,22.7,NaN

In [6]:
sierraleone_df.tail(15)

,Timestamp,GHI,DNI,DHI,ModA,ModB,Tamb,RH,WS,WSgust,WSstdev,WD,WDstdev,BP,Cleaning,Precipitation,TModA,TModB,Comments
525585,2022-10-29 23:46,-1.1,0.0,-2.5,0.0,0.0,23.9,100.0,0.0,0.0,0.0,0.0,0.0,1000,0,0.0,24.1,24.5,NaN
525586,2022-10-29 23:47,-1.1,0.0,-2.5,0.0,0.0,23.9,100.0,0.0,0.0,0.0,0.0,0.0,1000,0,0.0,24.2,24.5,NaN
525587,2022-10-29 23:48,-1.1,0.0,-2.5,0.0,0.0,23.9,100.0,0.0,0.0,0.0,0.0,0.0,1000,0,0.0,24.2,24.6,NaN
525588,2022-10-29 23:49,-1.1,0.0,-2.5,0.0,0.0,23.9,100.0,0.0,0.0,0.0,0.0,0.0,1000,0,0.0,24.2,24.6,NaN
525589,2022-10-29 23:50,-1.2,0.0,-2.4,0.0,0.0,24.0,100.0,0.2,0.7,0.4,148.9,2.5,1000,0,0.0,24.3,24.6,NaN
525590,2022-10-29 23:51,-1.2,-0.1,-2.3,0.0,0.0,24.0,100.0,0.0,0.0,0.0,0.0,0.0,1000,0,0.0,24.3,24.6,NaN
525591,2022-10-29 23:52,-1.2,-0.1,-2.3,0.0,0.0,24.0,100.0,0.0,0.0,0.0,0.0,0.0,1000,0,0.0,24.3,24.6,NaN
525592,2022-10-29 23:53,-1.3,-0.1,-2.4,0.0,0.0,24.0,100.0,0.0,0.0,0.0,0.0,0.0,1000,0,0.0,24.3,24.6,NaN
525593,2022-10-29 23:54,-1.4,-0.1,-2.5,0.0,0.0,24.0,100.0,0.0,0.0,0.0,0.0,0.0,1000,0,0.0,24.2,24.6,NaN
525594,2022-10-29 23:55,-1.5,-0.1,-2.7,0.0,0.0,24.0,100.0,0.0,0.0,0.0,0.0,0.0,1000,0,0.0,24.2,24.5,NaN
525595,2022-10-29 23:56,-1.6,-0.1,-2.9,0.0,0.0,24.0,100.0,0.0,0.0,0.0,0.0,0.0,999,0,0.0,24.2,24.5,NaN
525596,2022-10-29 23:57,-1.7,-0.1,-3.0,0.0,0.0,24.0,100.0,0.0,0.0,0.0,0.0,0.0,999,0,0.0,24.2,24.5,NaN
525597,2022-10-29 23:58,-1.7,-0.1,-3.1,0.0,0.0,24.0,100.0,0.0,0.0,0.0,0.0,0.0,1000,0,0.0,24.1,24.4,NaN
525598,2022-10-29 23:59,-1.7,-0.2,-3.3,0.0,0.0,23.9,100.0,0.0,0.0,0.0,0.0,0.0,1000,0,0.0,24.1,24.4,NaN
525599,2022-10-30 00:00,-1.7,-0.1,-3.4,0.0,0.0,23.9,100.0,0.0,0.0,0.0,0.0,0.0,1000,0,0.0,24.1,24.4,NaN

In [7]:
(sierraleone_df[["Cleaning"]] > 0).sum()

Cleaning    508
dtype: int64

In [8]:
# Shape or size of the datasets
print(f'Benin Dataset Shape: {sierraleone_df.shape}')

Benin Dataset Shape: (525600, 19)

In [9]:
sierraleone_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 525600 entries, 0 to 525599
Data columns (total 19 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   Timestamp      525600 non-null  object
 1   GHI            525600 non-null  float64
 2   DNI            525600 non-null  float64
 3   DHI            525600 non-null  float64
 4   ModA           525600 non-null  float64
 5   ModB           525600 non-null  float64
 6   Tamb           525600 non-null  float64
 7   RH             525600 non-null  float64
 8   WS             525600 non-null  float64
 9   WSgust         525600 non-null  float64
 10  WSstdev        525600 non-null  float64
 11  WD             525600 non-null  float64
 12  WDstdev        525600 non-null  float64
 13  BP             525600 non-null  int64
 14  Cleaning       525600 non-null  int64
 15  Precipitation  525600 non-null  float64
 16  TModA          525600 non-null  float64
 17  TModB          525600 non-null  float64
 18  Comments       0 non-null       float64
dtypes: float64(16), int64(2), object(1)
memory usage: 76.2+ MB

##Data Insights for Sierra Leone data

All columns are not having any null entries except Comments
From 18 not null columns 17 columns are numerical the left is categorical data